### ISSUE TITLE
Certificate folder location not found in Qlik Sense Desktop

### ISSUE THREAD

**Issue by saravana325da** [rileymd88/qwik-forecast-installer#1]
Hi, I am trying this qwik-forecast -installer in my qlik sense desktop, while installing, in the advance setting i cannot find the repository folder for certificate path.
![image](https://user-images.githubusercontent.com/42143093/81492050-5e2c0a80-92b2-11ea-9035-c730073ee5b9.png)

![image](https://user-images.githubusercontent.com/42143093/81492064-78fe7f00-92b2-11ea-9e99-deea657008b0.png)

is it possible to use this extension in Qlik sense Desktop? where i can find the certificate?

**Comment by rileymd88** [comment]
Hi @saravana325da 

Sorry at the moment the extension is not working for Qlik Sense Desktop.
